### ISSUE TITLE
Private final fields do not export

### ISSUE THREAD

**Issue by YuliaStrakhova** [devlauer/plantuml-generator#13] opened 2020-11-02 15:01 UTC
It  look like  private **final** fields do not export. 

My configuration: 

<plugin>
                    <artifactId>plantuml-generator-maven-plugin</artifactId>
                    <groupId>de.elnarion.maven</groupId>
                    <version>1.1.2</version>
                    <executions>
                        <execution>
                            <id>generate-simple-diagram</id>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                            <phase>generate-test-sources</phase>
                            <configuration>
                                <outputDirectory>target/generated-docs</outputDirectory>
                                <outputFilename>commands.plantuml</outputFilename>
                                <scanPackages>
                                    <scanPackage>XXXX</scanPackage>
                                </scanPackages>
                                <hideFields>false</hideFields>
                                <hideMethods>false</hideMethods>
                                <maxVisibilityFields>PRIVATE</maxVisibilityFields>
                                <maxVisibilityMethods>PUBLIC</maxVisibilityMethods>
                                <methodBlacklistRegexp>(hashCode|equals)</methodBlacklistRegexp>
                                <blacklistRegexp>.*\$.*|XXX.BeanConverter|.*\.metamodel\..*</blacklistRegexp>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

**Comment by YuliaStrakhova** [comment] 2020-11-02 15:06
`<plugin>
                    <artifactId>plantuml-generator-maven-plugin</artifactId>
                    <groupId>de.elnarion.maven</groupId>
                    <version>1.1.2</version>
                    <executions>
                        <execution>
                            <id>generate-simple-diagram</id>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                            <phase>generate-test-sources</phase>
                            <configuration>
                                <outputDirectory>target/generated-docs</outputDirectory>
                                <outputFilename>commands.plantuml</outputFilename>
                                <scanPackages>
                                    <scanPackage>com.xx.service.commands</scanPackage>
                                </scanPackages>
                                <hideFields>false</hideFields>
                                <hideMethods>false</hideMethods>
                                <maxVisibilityFields>PRIVATE</maxVisibilityFields>
                                <maxVisibilityMethods>PUBLIC</maxVisibilityMethods>
                                <methodBlacklistRegexp>(hashCode|equals)</methodBlacklistRegexp>
                                <blacklistRegexp>.*\$.*|com.xx.common.converter.BeanConverter|.*\.metamodel\..*</blacklistRegexp>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>`

**Comment by devlauer** [comment] 2020-11-29 14:39
Sorry for answering so late! I didn't have the time to investigate your issue until now.

Now I wanted to reproduce your issue but I did not succeed:
* I've added a testcase for private final fields to the plantuml-generator-util project which is the base for the maven-plugin but everything works as expected (Testcase T0022)
* I've added a testcase with the same pluginconfiguration as you used to the project4-module of the sample.asciidoc repository of mine (https://github.com/devlauer/sample.asciidoc/tree/master/project4) but the same here: everything works as expected.

Is something special about your constellation? Are the classes to scan in a dependent artifact? Which Java Version do you use? Which Maven Version do you use?

**Comment by devlauer** [comment] 2021-01-06 07:28
I am closing the issue. Feel free to reopen if the problem is still there.

**Closed by devlauer** 2021-01-06 07:28 UTC
